#ifndef BUFFER_ALLOCATION_H_
#define BUFFER_ALLOCATION_H_

#define BUFFER_SIZE            ( ipTOTAL_ETHERNET_FRAME_SIZE + ipBUFFER_PADDING )
#define BUFFER_SIZE_ROUNDED_UP ( ( BUFFER_SIZE + 7 ) & ~0x07UL )

/* EMAC variables located in AHB SRAM bank 1 and 2 */
#define AHB_SRAM_BANK1_BASE    0x2007C000UL

#define NETWORK_BUFFER_BASE    ( AHB_SRAM_BANK1_BASE )
#define NETWORK_BUFFER_END     ( NETWORK_BUFFER_BASE + ( ipconfigNUM_NETWORK_BUFFER_DESCRIPTORS * BUFFER_SIZE_ROUNDED_UP ) )

#endif /* BUFFER_ALLOCATION_H */
